
server:
  port: 8081

spring:
  application:
    name: 'provider'
    data:
      mongodb:
        uri: mongodb://localhost:27017/store

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka